name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t vishnumohanan/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push vishnumohanan/auth
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --region=GKE_REGION --project=GKE_PROJECT_ID
      - run: kubectl rollout restart deployment auth-depl
      
