name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}
      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --region=${{secrets.GKE_REGION}} --project=${{ secrets.GKE_PROJECT_ID }}
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
