name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --region=GKE_REGION --project=GKE_PROJECT_ID
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
